# 服务器配置
server:
  # 应用端口
  port: 8080
  # 上下文路径
  servlet:
    context-path: /api

# Spring配置
spring:
  application:
    name: soul-game-db


  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/soul_game_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Hwb2003108@@.
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA配置
  jpa:
    hibernate:
      # 数据库表更新策略：update表示自动更新表结构
      ddl-auto: update
    # 显示SQL语句
    show-sql: true
    properties:
      hibernate:
        # 格式化SQL输出
        format_sql: true
        # 数据库方言
        dialect: org.hibernate.dialect.MySQLDialect

# 日志配置
logging:
  level:
    # 项目包的日志级别
    com.soul.game.soulgamedb: DEBUG
    # SQL日志
    org.hibernate.SQL: DEBUG
    # SQL参数日志
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    # 自定义 Swagger HTML 页面的访问路径，默认是 /swagger-ui.html
    path: /swagger-ui.html
  api-docs:
    # 后端生成的 OpenAPI 规范 JSON 数据的接口路径
    path: /v3/api-docs
